### ISSUE TITLE
Evaluation？

### ISSUE THREAD

**Issue by yurenwei** [JunaidCS032/MOTBeyondPixels#10]
I am sorry to bother you. I want to know how you use the KITTI test set to evaluate your algorithm. I mainly want to know the label file of the KITTI test set because I did not find the label file of KITTI's test set.

**Comment by krrish94** [comment]
The labels of the KITTI test set aren't public (it's a 'test' set for a reason). So, you usually run the tracker on a bunch of sequences, and output your detections and associations in a text file format as specified by the KITTI tracking evaluation protocol, and upload your results to the evaluation server. The evaluation server compares your tracklets to the (non-public) ground-truth and computes performance metrics (MOTA, MOTP, etc.).

**Comment by yurenwei** [comment]
Dear professor,
Thank you very much for your help. Another question is how to divide which test sets are vehicles and pedestrians? Thank you very much for taking time out of your busy schedule to answer my question. I am looking forward to your reply.

At 2019-06-19 11:10:51, "Krishna Murthy" <notifications@github.com> wrote:


The labels of the KITTI test set aren't public (it's a 'test' set for a reason). So, you usually run the tracker on a bunch of sequences, and output your detections and associations in a text file format as specified by the KITTI tracking evaluation protocol, and upload your results to the evaluation server. The evaluation server compares your tracklets to the (non-public) ground-truth and computes performance metrics (MOTA, MOTP, etc.).
