### ISSUE TITLE
Where is the code about "Shape and Pose cost"

### ISSUE THREAD

**Issue by yukitsuji** [JunaidCS032/MOTBeyondPixels#4]
I can't find the code about "Shape and Pose cost".
Does this repository include its code?

Thanks!

**Comment by JunaidCS032** [comment]
No, the code for "Shape and Pose cost" is not included in this repository as this cost was not used for evaluating our results. 

However, the improvement caused by integrating this cost was reported in our paper, but as stated above, we did not used this while evaluation.
