### ISSUE TITLE
2D Feature Extraction Algorithm

### ISSUE THREAD

**Issue by johnlambert-argo** [JunaidCS032/MOTBeyondPixels#5]
Thank you very much for sharing your code!

Question -- how do you create the 2D features that are saved in `Features2D_mat`? I may have missed the description of the feature extraction algorithm. Could you also share this code?

**Comment by krrish94** [comment]
We use a variant of the stacked hourglass network and slice a few feature maps from particular layers that are responsive to distinct features of cars. The overall code could be tricky to work with, involving several dependencies; hence we released our extracted features directly as matrices.

In case you are further keen on getting the feature extractor and are willing to set up the dependencies, get in touch with us; we'll share that piece of code too.
