### ISSUE TITLE
About validation dataset

### ISSUE THREAD

**Issue by yukitsuji** [JunaidCS032/MOTBeyondPixels#6]
Did you evaluate the method using 'all training data' in Table 3 ?
If no, could you provide additional information?
<img width="713" alt="beyond_pixel" src="https://user-images.githubusercontent.com/9513712/50424713-46660900-08ac-11e9-9b87-b5d25084dce3.png">

Thanks in advance,

Yuki Tsuji

**Comment by JunaidCS032** [comment]
Yes, we evaluated over all the training sequences (excluding the ones which contain only pedestrians and no cars).

Best.
Junaid.
