### ISSUE TITLE
scale of camera motion.

### ISSUE THREAD

**Issue by jaehyuck0103** [JunaidCS032/MOTBeyondPixels#7]
Hello. Firstly, thank you for providing the code.

Here is one question about the camera motion.
To compensate one frame of ego motion, I expected the scale of camera motion values should be meters per 0.1 sec (as KITTI is 10 frames/sec).
But, when I check the camera motion values from ORB slam and scaling (1.72/44), the values seem to be too small.
Could you explain why such a small value?

**Comment by JunaidCS032** [comment]
Hi Jae-Hyuck,

Nice catch! I think the release version has a typo and is missing a division operator. Let me double check, and I'll push changes asap.

**Comment by krrish94** [comment]
Closing (inactivity)
