### ISSUE TITLE
Script for filtering detections

### ISSUE THREAD

**Issue by Kennard123661** [JunaidCS032/MOTBeyondPixels#8]
Hi! Thanks for putting up your code. I wasn't able to find the filtering scripts for both rccnet and subcnn detections in the downloaded Data dir. Would it be possible to share them? Thank you!

**Comment by JunaidCS032** [comment]
Hi Kennard, sure, let me check it with another colleague of mine who worked on this part of the paper. I will get back to you once I have some update.
